name: fl_common_lint
description: Common linter configuration for vanyasem's projects.
version: 1.2.0
homepage: https://github.com/vanyasem/fl-common-lint
repository: https://github.com/vanyasem/fl-common-lint
issue_tracker: https://github.com/vanyasem/fl-common-lint/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
